# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", "~> 4.4.0"

gem "just-the-docs", "0.10.1"

group :jekyll_plugins do
    gem 'jekyll_picture_tag', '~> 2.0'
  end

gem "csv"
gem "base64"
gem "logger"
